### ISSUE TITLE
Typo in blog post

### ISSUE THREAD

**Issue by almccon** [DylanMoriarty/DylanMoriarty.github.io#3]
In https://dylanmoriarty.github.io/blog/basketweavers-and-open-data.html
You write "These are major roads in OSM cropped to the United States, projected in a special version of albers that has Florida and Alaska positioned in the bottom left corner. Had I not cropped that data, these roads would indeed extend into Canada & Mexico. I'm also excluding tertiary & service roads, as well as footpaths, trails etc." but you really mean Hawaii instead of Florida.

Great blog post, by the way!

**Comment by DylanMoriarty** [comment]
🙇 

Thanks! Also, kudos for being the first person to log an issue on my personal site. I need a copy editor in my life, so I'm amazed it doesn't happen more often.
